#!/bin/sh

user=$(whoami)
date=`date`
load=`cat /proc/loadavg | awk '{print $1" (1min) "$2" (5min) "$3" (15min)"}'`
root_usage=`df -h / | awk '/\// {print $(NF-1)}'`
root_used=`df -h / | awk '/\// {print $(NF-2)}'`
root_total=`df -h / | awk '/\// {print $(NF-3)}'`
memory_usage=`awk '/Active/{free=$2} /MemTotal/{total=$2} END{printf("%3.1f%%", (free*100)/total)}' /proc/meminfo`
memory=`free -m | awk '/Mem:/ { print $2 }'`
memory_used=`free -m | awk '/Mem/ { print $3 }'`
swap_usage=`free -m | awk '/Partition/ { printf("%dMB %3.1f%%", $5, $5/$3*100) }'`
users=` w -s | grep -v WHAT | grep -v "load average" | wc -l`
logged=`who | awk '{print $1}' | uniq`
time=`uptime | awk -F'( |,|:)+' '{print $6,$7",",$8,"hours,",$9,"minutes"}'`
processes_total=`ps aux | wc -l`
processes_user=`ps -U ${user} u | wc -l`
cpu_temp=`sensors | grep °C | tr -d '+' | awk '/Package/ { print $4" (maxi "$7" critical "$10}'`
ip=`ifconfig $(route | grep default | awk '{ print $8 }') | grep "inet" | awk '{print $2}'`

echo "\033[1;37mSystem information as of: $date\033[0m"
echo "\033[1;31mSystem load....... \033[1;34m" $load
echo "\033[1;31mIP................ \033[1;34m" $ip
echo "\033[1;31mUptime............ \033[1;34m" "$time"
echo "\033[1;31mCPU temperature... \033[1;34m" "$cpu_temp"
echo "\033[1;31mMemory usage...... \033[1;34m" "using" $memory_used"/"$memory" MB ("$memory_usage")"
echo "\033[1;31mUsage on /........ \033[1;34m" $root_used"/"$root_total "("$root_usage")"
echo "\033[1;31mSwap usage........ \033[1;34m" $swap_usage
echo "\033[1;31mSSH logins........ \033[1;34m" $users "opened SSH sessions"
echo "\033[1;31mProcesses......... \033[1;34m" $processes_total "total," $processes_user "yours"
echo "\033[1;31mCurrently logged.. \033[1;34m" $logged
echo "\033[37m"
